In [21]:
import numpy as np
np.__version__

'1.26.4'

In [2]:
a = np.array(0)
a, a.ndim, type(a)
#a는 그냥 0이아니고 array0이고 a는 0차원)

(array(0), 0, numpy.ndarray)

In [3]:
a= np.array([2,4,6])
a, a.ndim

(array([2, 4, 6]), 1)

In [7]:
#2차원은 리스트 2개로 표현
a = np.array([[1,2,3],[4,5,6]])
a, a.ndim

(array([[1, 2, 3],
        [4, 5, 6]]),
 2)

In [10]:
a = np.array([[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]])
a, a.ndim, a.shape
#2행3열이 2개 있어

(array([[[1, 2, 3],
         [4, 5, 6]],
 
        [[1, 2, 3],
         [4, 5, 6]]]),
 3,
 (2, 2, 3))

In [ ]:
#shpae (행렬의 차원을 반환)


In [12]:
a = np.array( [ [[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]],[[1,2,3], [4,5,6]] ] )
a.shape

(3, 2, 3)

In [13]:
a= np.array([[1,2,3 ],[10,20,30],[100,200,300]])
a, a.ndim, a.shape


(array([[  1,   2,   3],
        [ 10,  20,  30],
        [100, 200, 300]]),
 2,
 (3, 3))

In [14]:
a = np.arange(15).reshape(3, 5)
a[0, 0]

0

In [17]:
matrix_b = np.arange(12).reshape(3,4)
matrix_b[0][0]

0

In [20]:
a = np.arange(15).reshape(3, -1)
a.shape, a.ndim

((3, 5), 2)

In [22]:
a = np.arange(15).reshape(3, -1)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [23]:
a.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [32]:
a = np.random.randint(1,100,(5,6))
a

array([[83, 12, 93, 93,  1, 54],
       [72, 25, 78, 54, 60, 83],
       [22, 88,  7, 95, 39, 39],
       [15, 61, 18, 79, 44, 36],
       [38,  9, 16, 99, 82,  3]])

In [35]:
a = np.random.randint(1,100,(5,6))
a[~(a>=10) & (a<=90)]

array([3, 3])

In [36]:
matrix = np.random.randint(1, 100, 30)
matrix, matrix[(matrix < 10) | (matrix > 90)]

(array([47, 51, 47, 39, 32, 73, 41, 66, 82, 59, 81, 70, 20, 35,  3, 93, 57,
        73, 86, 75, 61, 81, 49, 23, 71, 88, 84, 71,  4, 18]),
 array([ 3, 93,  4]))